server:
  port: 8800
spring:
  application:
    name: service-trade
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    url: jdbc:mysql://47.105.194.89:32306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 47.105.178.19
    port: 31379
    password: 
    pool:
      maxActive: 200
      maxWait: -1
      maxIdel: 10
      minIdel: 0
    timeout: 1000
mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
logging:
  level:
    com.demo2.trade: DEBUG
    com.demo2.support: DEBUG